#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.group_name = "public with space"
    args.group_description = "My public space"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.a8bb33c7.name = "Upgrade from 0.8.2~ynh1"
    test_upgrade_from.88b2f8e456548c7624ca5029fc562a79b3cd0401.name = "Upgrade from 0.96.3~ynh1"
